"""Bounds-propagation search strategy.

This is a port of the Molnar-Singh algorithm from
https://github.com/grantmolnar/Spoof-Lehmer-Factorizations, integrated
with the rest of the architecture.

Algorithm sketch
----------------
A "partial state" is a sorted prefix of factors (x_1, ..., x_s) with
s <= r and a target k. We maintain two integer-valued bounds on the
ratio k(F) = (eps - 1) / phi* over all completions of the prefix:

    L(prefix) = (eps - 1) / phi*               (s == r case)
              = eps / phi*                     (s < r case)
                attained as remaining factors -> infinity

    U(prefix) = (eps' - 1) / phi*'             where eps' and phi*'
                are computed by filling all remaining slots with the
                smallest legal next factor (the current max factor).

Both bounds approach the shared limit eps/phi* as the next factor
grows: L from below, U from above. Pruning rule: if U < k for the
target k, no completion of this prefix can give a k-Lehmer
factorization.

The brilliant property is that this gives termination *without* an
a priori bound on epsilon. The "max_N" parameter that the recurrence
strategy needs is replaced by the natural termination of the next-factor
loop, which always halts because U decreases monotonically toward the
shared limit.

Two implementation notes:

1. We never construct sympy.Fraction objects on the hot path. The
   bound comparisons L <= k and U < k are written as cross-multiplied
   integer comparisons, which are 10-100x faster than Fraction().

2. We use a single mutable factors list throughout the recursion,
   appending before recursing and popping after. This avoids the
   per-node list-copy allocation cost.

Pruning rule from Lehmer (Theorem 2): no factor of a Lehmer
factorization can be congruent to 1 mod another factor. We check
this at every candidate.
"""
from __future__ import annotations
from collections.abc import Callable
from datetime import datetime, timezone
from math import isqrt

from sympy import divisors, isprime  # type: ignore[import-untyped]
from sympy.ntheory.generate import primerange  # type: ignore[import-untyped]

from spoof_lehmer.domain import Factorization
from spoof_lehmer.storage import FactorizationRepository, Provenance
from spoof_lehmer.tracking import RunResult, RunStatus, RunRecord


# Small primes used by the cheap pre-factorization residue filter in
# finish_two. Trial-dividing M by primes < 200 is ~70% as effective at
# pruning as primes < 1000 but ~5x faster, so 200 is the sweet spot.
_SMALL_PRIMES_FOR_FILTER: tuple[int, ...] = tuple(primerange(2, 200))


def _has_divisor_in_residue_class(
    M: int, A: int, target: int,
) -> bool:
    """Cheap necessary test: does M have any divisor d with d % A == target?

    Returns True if the test is inconclusive (must factor M to know);
    returns False only if no divisor of M can be in target's class.

    Method: trial-divide M by primes in _SMALL_PRIMES_FOR_FILTER to
    extract the smooth part. Build the multiplicative reachable set
    in (Z/A) generated by the smooth factors. If the unfactored
    residual is 1 or prime, the answer is exact. Otherwise the
    residual is composite of primes coprime to A (since we trial-
    divided every small prime that could divide A); those unknown
    primes are units mod A, so the residual contributes "any unit
    mod A" to the reachable set. We accept (return True) iff the
    target is a unit mod A or already in the smooth-reachable set.
    """
    if A <= 1:
        return True
    # Trial-divide M by small primes.
    sf: dict[int, int] = {}
    rem = M
    for p in _SMALL_PRIMES_FOR_FILTER:
        if p * p > rem:
            break
        while rem % p == 0:
            sf[p] = sf.get(p, 0) + 1
            rem //= p
    # Build reachable set from smooth factors.
    reached: set[int] = {1 % A}
    for p, e in sf.items():
        new_reached: set[int] = set()
        p_mod = p % A
        for r in reached:
            pk = 1
            for _ in range(e + 1):
                new_reached.add((r * pk) % A)
                pk = (pk * p_mod) % A
        reached = new_reached
    # Handle residual.
    if rem == 1:
        return target in reached
    if isprime(rem):
        rem_mod = rem % A
        if target in reached:
            return True
        return any(target == (r * rem_mod) % A for r in reached)
    # rem is composite, unknown primes — all coprime to A.
    if target in reached:
        return True
    # Unknown primes are units mod A; their products are units; so
    # divisors of rem reach every unit residue class. If target is a
    # unit mod A, reachable. Otherwise, only reachable via smooth
    # factors (already checked).
    from math import gcd
    return gcd(target, A) == 1


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


class BoundsPropagationStrategy:
    """Find all k-Lehmer factorizations with exactly r factors, for all
    relevant k, using monotone bounds on k(F).

    Unlike RecurrenceStrategy, this strategy does NOT take a max_N
    parameter. Termination comes from the bounds tightening, not from a
    box cutoff. This makes it the right tool for proving exhaustive
    completeness at length r without an a priori epsilon bound.

    For each r in [2, max_r], the strategy:
      1. Computes the (finite!) range of k values worth searching.
      2. For each such k, walks the prefix tree with bounds-driven pruning.
      3. Yields every prefix that completes to a k-Lehmer factorization.

    Plus-seeds (k * phi* = eps + 1) are NOT discovered by this strategy
    in its current form - it targets only k-Lehmer factorizations. The
    recurrence strategy still owns plus-seed discovery.
    """
    name = "bounds_propagation"

    def __init__(
        self,
        k_target: int,
        max_r: int = 7,
        min_r: int = 2,
        is_even: bool = False,
        use_finishing_feasibility: bool = True,
        use_finish_three: bool = False,
        use_residue_filter: bool = True,
        on_found: "Callable[[Factorization], None] | None" = None,
    ):
        """
        Args:
            k_target: the value of k in k * phi*(F) = eps(F) - 1.
            max_r: enumerate factorizations of length min_r..max_r inclusive.
            min_r: smallest length to enumerate (default 2). Set equal to
                max_r to search only one r.
            is_even: if True, factors must be >= 2 (even spoof). Default
                False means factors must be >= 3 and odd (the original
                paper's restriction).
            use_finishing_feasibility: if True (default), solve the last
                two levels (s = r-1 and s = r-2) in closed form via the
                finishing-feasibility identities rather than by the
                bounds-propagation loop.
            use_finish_three: if True, additionally solve s = r-3 via
                the partial closed form of Proposition 3. Default False.
            use_residue_filter: if True (default), apply the cheap
                pre-factorization residue filter inside finish_two
                that prunes prefixes whose M = B*E - A has no divisor
                in the required residue class mod A. Empirically
                ~60% pruning at the r=7 Fermat-4 prefix.
            on_found: optional callback invoked once per newly-added
                factorization (i.e. ones that survive repo.add()'s
                dedup check). Lets callers stream progress without
                wrapping the repository.
        """
        self.k_target = k_target
        self.max_r = max_r
        self.min_r = min_r
        self.is_even = is_even
        self.use_finishing_feasibility = use_finishing_feasibility
        self.use_finish_three = use_finish_three
        self.use_residue_filter = use_residue_filter
        self.on_found = on_found

    def discover(self, repo: FactorizationRepository) -> RunResult:
        record = RunRecord.started_now(
            self.name, self.k_target, self.max_r, max_N=None,
        )
        added = 0
        nodes = 0
        for r in range(self.min_r, self.max_r + 1):
            sub_added, sub_nodes = self._search_at_length(repo, r)
            added += sub_added
            nodes += sub_nodes

        result = RunResult(
            added=added, status=RunStatus.COMPLETE, nodes_explored=nodes,
            notes=f"k_target={self.k_target}, no max_N (bounds-driven termination)",
        )
        record.finish(result)
        repo.record_run(record)
        return result

    def discover_subtree(
        self, repo: FactorizationRepository, prefix: tuple[int, ...],
    ) -> RunResult:
        """Enumerate factorizations of length min_r..max_r whose first
        len(prefix) factors equal prefix.

        Used by parallel coordinators to partition a single (r, k)
        search across many workers, each handling one prefix subtree.
        Does NOT write a RunRecord (the coordinator owns run tracking
        for the partitioned search).
        """
        added = 0
        nodes = 0
        for r in range(self.min_r, self.max_r + 1):
            if len(prefix) > r:
                continue
            sub_added, sub_nodes = self._search_at_length(repo, r, prefix)
            added += sub_added
            nodes += sub_nodes
        return RunResult(
            added=added, status=RunStatus.COMPLETE, nodes_explored=nodes,
            notes=f"k_target={self.k_target}, prefix={prefix}",
        )

    def _search_at_length(
        self, repo: FactorizationRepository, r: int,
        prefix: tuple[int, ...] = (),
    ) -> tuple[int, int]:
        """Enumerate every k-Lehmer factorization of length exactly r
        whose first len(prefix) factors equal prefix.

        prefix=() (default) searches the full space, matching the
        original behavior. A non-empty prefix restricts the search to
        the subtree rooted at that prefix; this is the entry point
        used for parallel partitioning.

        Caller is responsible for ensuring the prefix is sorted, of
        length < r, and obeys parity / Lehmer-congruence among its own
        elements. We do NOT re-validate the prefix here.
        """
        added = 0
        nodes = [0]

        # Mutable state shared across the recursion.
        factors: list[int] = list(prefix)
        # eps and phi* maintained incrementally.
        # eps = product of factors so far (1 if empty)
        # phi = product of (x_i - 1) so far (1 if empty)
        k = self.k_target
        min_first = 2 if self.is_even else 3
        step = 1 if self.is_even else 2

        use_ff = self.use_finishing_feasibility
        use_ff3 = self.use_finish_three
        use_residue_filter = self.use_residue_filter
        parity_ok = (lambda v: True) if self.is_even else (lambda v: v % 2 == 1)

        def emit(extra: tuple[int, ...]) -> None:
            nonlocal added
            fact = Factorization(tuple(factors) + extra, self.k_target)
            if repo.add(fact, Provenance(self.name, None, _now())):
                added += 1
                if self.on_found is not None:
                    self.on_found(fact)

        def congruence_ok_against_prefix(v: int) -> bool:
            for x in factors:
                if (v - 1) % x == 0:
                    return False
            return True

        def finish_one(eps: int, phi: int, min_a: int) -> None:
            # s = r-1: k*P*(x-1) = E*x - 1  =>  x = (kP - 1)/(kP - E).
            kP = k * phi
            A = kP - eps  # kP - E
            if A <= 0:
                return
            num = kP - 1
            if num % A != 0:
                return
            x = num // A
            if x < min_a or not parity_ok(x):
                return
            if not congruence_ok_against_prefix(x):
                return
            emit((x,))

        def finish_two(eps: int, phi: int, min_a: int) -> None:
            # s = r-2: (A*a - B)(A*b - B) = B*E - A
            # with A = kP - E, B = kP.
            #
            # We need all divisors d of M = B*E - A in the half-line
            # [max(1, A*min_a - B), isqrt(M)]. We use sympy.divisors
            # to factor M (Pollard-rho / ECM under the hood), then
            # filter for the residue and range constraints.
            #
            # Pre-filter: for d to give an integer (a, b), we need
            # d ≡ -B (mod A). Many candidate prefixes have NO divisor
            # of M in this residue class, but factoring M still costs
            # ~ms. The cheap residue test trial-divides M by primes
            # < 200 and rules out hopeless cases without paying for
            # the full factorization. Empirically prunes ~60% of the
            # x_5 loop iterations at the r=7 Fermat-4 prefix.
            kP = k * phi
            A = kP - eps
            B = kP
            if A <= 0:
                return
            M = B * eps - A
            if M <= 0:
                return
            d1_min_raw = A * min_a - B
            d1_lo = d1_min_raw if d1_min_raw > 0 else 1
            d1_hi = isqrt(M)
            if d1_lo > d1_hi:
                return
            if use_residue_filter:
                target = (-B) % A
                if not _has_divisor_in_residue_class(M, A, target):
                    return
            # Get every divisor of M in [d1_lo, d1_hi].
            for d1 in divisors(M):
                if d1 < d1_lo:
                    continue
                if d1 > d1_hi:
                    break
                d2 = M // d1
                ax = d1 + B
                bx = d2 + B
                if ax % A == 0 and bx % A == 0:
                    a = ax // A
                    b = bx // A
                    if min_a <= a <= b and parity_ok(a) and parity_ok(b):
                        if congruence_ok_against_prefix(a):
                            if congruence_ok_against_prefix(b) and (b - 1) % a != 0:
                                emit((a, b))

        def finish_three(eps: int, phi: int, min_a: int) -> None:
            """s = r-3: triples (a, b, c) with a <= b <= c.

            The defining equation
              k*P*(a-1)(b-1)(c-1) = E*a*b*c - 1
            rearranges (with A = kP - E, B = kP, and substitutions
            u = Aa - B, v = Ab - B, w = Ac - B) to
              u*v*w - E*B*(u + v + w) = C
            where C = A^2 * (E - 1) + E^2 * (3*A + 2*E).

            For each fixed u >= 1 with (u + B) divisible by A, this
            collapses to a two-variable equation of the same shape
            as finish_two:
              (u*v - E*B)(u*w - E*B) = u*C + u^2*E*B + (E*B)^2.

            We iterate u from its minimum (set by a >= min_a) upward
            and delegate to a finish_two-style divisor enumeration
            per u.

            This is a structural analogue of finish_two, not a
            dramatic speedup: the outer u loop runs through the
            same set of integer a values that search() would visit.
            Its value is correctness-by-construction (no recursion
            into candidate pruning logic) and clarity.
            """
            kP = k * phi
            A = kP - eps
            B = kP
            if A <= 0:
                return
            EB = eps * B
            C = A * A * (eps - 1) + eps * eps * (3 * A + 2 * eps)

            # Smallest u consistent with a >= min_a:
            #   u_min = A * min_a - B, clamped to >= 1
            u_min = A * min_a - B
            if u_min < 1:
                u_min = 1
            # u must satisfy (u + B) divisible by A so that a is integer.
            # Align u_min to that residue class. Target residue: (-B) mod A.
            target_mod = (-B) % A
            shift = (target_mod - (u_min % A)) % A
            u = u_min + shift

            # Upper bound on u: any valid triple has u <= v <= w, so
            # u^3 <= u*v*w = E*B*(u+v+w) + C <= E*B*(3*w) + C.
            # Using v, w <= w and u <= w: u <= w, but w is the unknown.
            # Safer: use the bounds-propagation termination -- at depth
            # r-3 the upper-bound test U >= k eventually fires. We
            # conservatively cap u at A * a_max - B where a_max is a
            # large enough cutoff. The parent search() already
            # bounded the a loop via U-test; we mirror that here by
            # checking whether the three-factor completion upper
            # bound U3(a) = (E*a^3 - 1) / (P*(a-1)^3) >= k.
            while True:
                # Recover a.
                if (u + B) % A != 0:
                    # Shouldn't happen given our alignment, but defensive.
                    u += A
                    continue
                a = (u + B) // A
                if a < min_a:
                    u += A
                    continue
                if not parity_ok(a):
                    # Advance u by A steps to preserve the
                    # divisibility condition; parity check still
                    # required on recovered a.
                    u += A
                    continue

                # Upper-bound check: U3(a) >= k?
                # E*a^3 - 1 >= k*P*(a-1)^3 required for any completion.
                if eps * a * a * a - 1 < k * phi * (a - 1) ** 3:
                    return

                # Lehmer congruence for a against the prefix.
                if not congruence_ok_against_prefix(a):
                    u += A
                    continue

                # Now solve for (b, c) via the two-variable reduction.
                # (u*v - E*B)(u*w - E*B) = M_u
                M_u = u * C + u * u * EB + EB * EB
                if M_u <= 0:
                    u += A
                    continue

                # Divisor enumeration. D1 = u*v - EB, D2 = u*w - EB,
                # with v = (D1 + EB) / u >= a (since b >= a).
                # b = (v + B) / A must be integer; so (v + B) % A == 0.
                # v = (D1 + EB) / u; we need (D1 + EB) % u == 0.
                # And (v + B) = ((D1 + EB) + uB) / u ... easier to
                # recover v first, then check b integrality.
                # Same for w.
                D1_min_from_b = u * (A * a - B) - EB  # enforces b >= a
                # Actually b >= a <=> v >= u <=> D1 >= u*u - EB;
                # but we're iterating D1 <= isqrt(M_u) so v <= w
                # automatically implies D1 <= D2.
                # Use D1 >= max(1, u*u - EB) for b >= a.
                D1_lo = max(1, u * u - EB)
                if D1_lo < 1:
                    D1_lo = 1
                D1_hi = isqrt(M_u)
                if D1_lo > D1_hi:
                    u += A
                    continue
                for D1 in divisors(M_u):
                    if D1 < D1_lo:
                        continue
                    if D1 > D1_hi:
                        break
                    D2 = M_u // D1
                    if (D1 + EB) % u == 0 and (D2 + EB) % u == 0:
                        v_val = (D1 + EB) // u
                        w_val = (D2 + EB) // u
                        if (v_val + B) % A == 0 and (w_val + B) % A == 0:
                            b = (v_val + B) // A
                            c = (w_val + B) // A
                            if (a <= b <= c
                                    and parity_ok(b) and parity_ok(c)
                                    and congruence_ok_against_prefix(b)
                                    and congruence_ok_against_prefix(c)
                                    and (b - 1) % a != 0
                                    and (c - 1) % a != 0
                                    and (c - 1) % b != 0):
                                emit((a, b, c))

                u += A  # next a in the integer ladder
                _ = D1_min_from_b  # silence lint (reserved for future tightening)

        def search(eps: int, phi: int, min_a: int, remaining: int) -> None:
            nonlocal added
            nodes[0] += 1

            if remaining == 0:
                # Terminal. Check k * phi == eps - 1.
                if k * phi == eps - 1:
                    fact = Factorization(tuple(factors), self.k_target)
                    if repo.add(fact, Provenance(self.name, None, _now())):
                        added += 1
                return

            if use_ff and remaining == 1:
                finish_one(eps, phi, min_a)
                return
            if use_ff and remaining == 2:
                finish_two(eps, phi, min_a)
                return
            if use_ff3 and remaining == 3:
                finish_three(eps, phi, min_a)
                return

            # Iterate next factor a >= min_a.
            # Lower bound on k(F) for any completion:
            #     L = eps / phi   (with all remaining factors -> infinity)
            # Upper bound (with all remaining factors set to a):
            #     eps_a = eps * a^remaining
            #     phi_a = phi * (a - 1)^remaining
            #     U = (eps_a - 1) / phi_a
            #
            # We want L <= k and U >= k. As a -> infinity, both L and U
            # approach eps/phi. So once U < k, every larger a also has
            # U < k, and we break.
            #
            # Cross-multiplied integer comparisons:
            #     L <= k       <=>  eps <= k * phi
            #     U >= k       <=>  eps_a - 1 >= k * phi_a
            #     U <  k       <=>  eps_a - 1 <  k * phi_a
            #
            # The lower bound L is monotone in factors but does NOT
            # depend on `a` - it's the same for every candidate at this
            # level. Compute it once.
            lower_ok = eps <= k * phi
            if not lower_ok:
                # No completion can give k(F) <= k anymore.
                # But we still need to check if the current prefix
                # itself happens to satisfy the equation - it can't,
                # because remaining > 0.
                return

            a = min_a
            while True:
                nodes[0] += 1
                # Upper-bound check first: as a grows, U decreases
                # monotonically. Once U < k, every larger a also fails.
                # U(prefix + a + (remaining-1) copies of a) >= k iff
                #   eps * a^remaining - 1 >= k * phi * (a-1)^remaining
                # Use Python's ** which is O(log n) and stays in C.
                a_pow = a ** remaining
                am1_pow = (a - 1) ** remaining
                if eps * a_pow - 1 < k * phi * am1_pow:
                    break

                # Lehmer congruence pruning: a != 1 mod x for any
                # existing factor x.
                congruence_ok = True
                for x in factors:
                    if (a - 1) % x == 0:
                        congruence_ok = False
                        break

                if congruence_ok:
                    new_eps = eps * a
                    new_phi = phi * (a - 1)
                    factors.append(a)
                    search(new_eps, new_phi, a, remaining - 1)
                    factors.pop()

                a += step

                if a > 10**12:
                    break

        # Initial call: factors already pre-loaded with prefix.
        # Compute starting (eps, phi, min_a, remaining) from the prefix.
        eps0 = 1
        phi0 = 1
        for x in factors:
            eps0 *= x
            phi0 *= (x - 1)
        min_a0 = factors[-1] if factors else min_first
        remaining0 = r - len(factors)
        if remaining0 < 0:
            # Caller asked for r shorter than the prefix; nothing to do.
            return added, nodes[0]
        search(eps=eps0, phi=phi0, min_a=min_a0, remaining=remaining0)
        return added, nodes[0]
